### ISSUE TITLE
how to get the selected value, for example when clicking the trash icon?

### ISSUE THREAD

**Issue by harysay** [nt4f04uNd/flutter_fancy_selection_demo#1]
`actionsSelection: [
            SizedBox.fromSize(size: const Size(48.0, 48.0)),
            IconButton(
              icon: const Icon(Icons.check_circle),
              onPressed: () {
               // How can I get all the selected values, so that I delete them based on the selected id?
                // Show deletion dialog....
              },
            ),
          ],`

**Comment by nt4f04uNd** [comment]
Consider using  [`showDialog`](https://api.flutter.dev/flutter/material/showDialog.html) from the Flutter framework to do this. 

You can also use [`showGeneralDialog`](https://api.flutter.dev/flutter/widgets/showGeneralDialog.html) if you want to define more custom animations of a dialog, and which is also used inside the `showDialog` internally.

Here is an example of how I use them in my own application, if this will be helpful.
I define my own showDialog [here](https://github.com/nt4f04uNd/sweyer/blob/7d1534b4831794670a5037d3d66c858aa2c045dc/lib/components/util/show_functions.dart#L121) and then use it [here](https://github.com/nt4f04uNd/sweyer/blob/7d1534b4831794670a5037d3d66c858aa2c045dc/lib/routes/initial_route.dart#L107) in the  `_handleDelete` method.

**Comment by nt4f04uNd** [comment]
Oh, excuse me, I guess I misunderstood what the issue is. There's a selectionSet property in SelectionController.

**Comment by harysay** [comment]
Ok, thks,..
if I see something like the example in the SelectionController sweyer application it only holds 1 parameter toss which is the id to delete. What if more than one parameter is thrown (not only the id but also the name and date selected). What should I do?

**Comment by nt4f04uNd** [comment]
I don't understand why would you even need this, it feels kind of wrong. You have some state already from which you render your list, just search for items by ids in that state if you want to delete them.

Though if you still want it for some reason, no one restricts you with the generic type of the `selectionController<T>`. This generic parameter is passed to `Set<T> selectionSet`, so no one restricts you, you can hold there classes or maps or whatever you want.
